-- ============================================================================
-- SCHEMA EXPORT — run this in the Supabase SQL Editor
--   Dashboard -> SQL Editor -> New query -> paste -> Run
--
-- No database password required: the SQL Editor authenticates with your
-- dashboard login. This sidesteps pg_dump entirely.
--
-- Returns ONE row, ONE column ("schema_ddl") containing the whole schema.
-- Click the cell, copy the full value, save it as supabase/schema.sql
--
-- Verified 2026-08-13 against project wqizwluccqqfkedpgvve (PostgreSQL 17.6):
--   241 statements / ~112 KB
--   8 enums, 41 tables, 47 constraints, 81 indexes, 43 functions,
--   9 views+matviews, 12 triggers
--
-- Deliberately EXCLUDED:
--   * objects owned by extensions (pg_trgm etc.) - 31 functions. pg_dump
--     omits these too; they come back via CREATE EXTENSION.
--   * RLS and policies - already captured in rls_policies.sql
--   NOTE: table and function GRANTs ARE included (ord 8). pg_get_functiondef()
--   omits them, so they must be emitted separately or they are silently lost.
--   * table DATA - schema only
--
-- CAVEAT: reconstructed from catalog, not produced by pg_dump. Ordering is
-- by object class, not dependency, so it is a faithful RECORD rather than a
-- guaranteed clean replay. Test against a scratch database before relying on
-- it to rebuild.
-- ============================================================================

with ext as (
  select objid from pg_depend
  where refclassid = 'pg_extension'::regclass and deptype = 'e'
),
enums as (
  select 1 ord, t.typname nm,
    'create type public.' || quote_ident(t.typname) || ' as enum (' ||
    (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)
       from pg_enum e where e.enumtypid = t.oid) || ');' s
  from pg_type t join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public' and t.typtype = 'e' and t.oid not in (select objid from ext)
),
tbls as (
  select 2 ord, c.relname nm,
    'create table if not exists public.' || quote_ident(c.relname) || E' (\n  ' ||
    (select string_agg(
        quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
        || case a.attidentity
             when 'a' then ' generated always as identity'
             when 'd' then ' generated by default as identity' else '' end
        || case when a.attgenerated = 's'
                  then ' generated always as (' || pg_get_expr(ad.adbin, ad.adrelid) || ') stored'
                when ad.adbin is not null
                  then ' default ' || pg_get_expr(ad.adbin, ad.adrelid)
                else '' end
        || case when a.attnotnull then ' not null' else '' end,
        E',\n  ' order by a.attnum)
      from pg_attribute a
      left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
      where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped)
    || E'\n);' s
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.oid not in (select objid from ext)
),
cons as (
  select 3 ord, rel.relname nm,
    'alter table public.' || quote_ident(rel.relname) ||
    ' add constraint ' || quote_ident(con.conname) || ' ' ||
    pg_get_constraintdef(con.oid) || ';' s
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace n on n.oid = rel.relnamespace
  where n.nspname = 'public'
),
idx as (
  select 4 ord, i.tablename nm, i.indexdef || ';' s
  from pg_indexes i
  where i.schemaname = 'public'
    and not exists (select 1 from pg_constraint c2
                    where c2.conname = i.indexname
                      and c2.connamespace = 'public'::regnamespace)
),
fns as (
  select 5 ord, p.proname nm, pg_get_functiondef(p.oid) || ';' s
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f','p')
    and p.oid not in (select objid from ext)
),
vws as (
  select 6 ord, c.relname nm,
    'create ' || case c.relkind when 'm' then 'materialized view' else 'or replace view' end ||
    ' public.' || quote_ident(c.relname) || E' as\n' || pg_get_viewdef(c.oid, true) ||
    case c.relkind when 'm' then ' with no data;' else '' end s
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('v','m')
    and c.oid not in (select objid from ext)
),
trg as (
  select 7 ord, c.relname nm, pg_get_triggerdef(tg.oid) || ';' s
  from pg_trigger tg
  join pg_class c on c.oid = tg.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not tg.tgisinternal
),
grants as (
  select 8 ord, c.relname nm,
    'grant ' || a.privilege_type || ' on table public.' || quote_ident(c.relname)
      || ' to ' || a.grantee::regrole::text || ';' s
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  cross join lateral aclexplode(c.relacl) a
  where n.nspname = 'public' and c.relkind in ('r','v','m')
    and a.grantee::regrole::text not in ('postgres','-')
  union all
  select 8 ord, p.proname nm,
    'grant ' || a.privilege_type || ' on function public.' || p.proname
      || '(' || pg_get_function_identity_arguments(p.oid) || ') to '
      || a.grantee::regrole::text || ';' s
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  cross join lateral aclexplode(p.proacl) a
  where n.nspname = 'public' and p.oid not in (select objid from ext)
    and a.grantee::regrole::text not in ('postgres','-')
),
allp as (
  select * from enums union all select * from tbls  union all select * from cons
  union all select * from idx   union all select * from fns   union all select * from vws
  union all select * from trg   union all select * from grants
)
select
  '-- Schema snapshot for public (project wqizwluccqqfkedpgvve)' || E'\n' ||
  '-- Generated by export_schema.sql. Reference record, not a migration.' || E'\n' ||
  '-- Statements: ' || count(*)::text || E'\n\n' ||
  string_agg(s, E'\n\n' order by ord, nm) as schema_ddl
from allp;
